"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.sample_bookings = void 0;
exports.sample_bookings = [
    {
        _id: "1",
        country: "France",
        region: "Île-de-France",
        town: "Paris",
        localization: "Paris, France, Île-de-France, Ile-de-France, Île de France, Ile de France",
        category: "Hebergements_Populaires",
        tags: ["Tous", "Romantique"],
        imgUrl: "../../../assets/img/france/marseille/populaires/hotel_le_soleil_du_matin.jpg",
        name: "Hôtel Le Soleil du matin",
        price: 128,
        stars: 5.0,
        description: " Au soleil, plongez-vous chaque jours",
        available: true,
        recorded: false,
        isPopulaire: true,
    },
    {
        _id: "2",
        country: "France",
        region: "Provence-Alpes-Côte d'Azur",
        town: "Marseille",
        localization: "Marseille, France, Provence-Alpes-Côte d'Azur, Provence-Alpes-Cote d'Azur, Provence Alpes Côte d'Azur, Provence Alpes Cote d'Azur ",
        category: "Hebergements_Populaires",
        tags: ["Tous", "Familial"],
        imgUrl: "../../../assets/img/france/marseille/populaires/au_coeur_de_leau_chambres_dhotes.jpg",
        name: "Au coeur de l'eau Chambres d'hôtes",
        price: 71,
        stars: 4.0,
        description: " Vivez cachées, vivez heureux",
        available: true,
        recorded: false,
        isPopulaire: true,
    },
    {
        _id: "3",
        country: "France",
        region: "Provence-Alpes-Côte d'Azur",
        town: "Marseille",
        localization: "Marseille, France, Provence-Alpes-Côte d'Azur, Provence-Alpes-Cote d'Azur, Provence Alpes Côte d'Azur, Provence Alpes Cote d'Azur ",
        category: "Hebergements_Populaires",
        tags: ["Tous", "Familial", "Romantique"],
        imgUrl: "../../../assets/img/france/marseille/populaires/hotel_tout_bleu_et_blanc.jpg",
        name: "Hôtel Tout bleu et Blanc",
        price: 68,
        stars: 4.0,
        description: " Bienvenue à la famille ",
        available: true,
        recorded: false,
        isPopulaire: true,
    },
    {
        _id: "4",
        country: "France",
        region: "Île-de-France",
        town: "Paris",
        localization: "Paris, France, Île-de-France, Ile-de-France, Île de France, Ile de France",
        category: "Hebergements",
        tags: ["Tous", "Economique", "Familial", "Animaux Autorisés"],
        imgUrl: "../../../assets/img/france/marseille/hebergements/auberge_la_cannebiere.jpg",
        name: "Auberge La Cannebière",
        price: 25,
        stars: 4.0,
        description: " Pour tous ",
        available: true,
        recorded: false,
        isHebergement: true,
    },
    {
        _id: "5",
        country: "France",
        region: "Provence-Alpes-Côte d'Azur",
        town: "Marseille",
        localization: "Marseille, France, Provence-Alpes-Côte d'Azur, Provence-Alpes-Cote d'Azur, Provence Alpes Côte d'Azur, Provence Alpes Cote d'Azur ",
        category: "Hebergements",
        tags: ["Tous", "Familial"],
        imgUrl: "../../../assets/img/france/marseille/hebergements/hotel_du_port.jpg",
        name: "Hôtel du port",
        price: 52,
        stars: 5.0,
        description: " Profitez avec votre famille ",
        available: true,
        recorded: false,
        isHebergement: true,
    },
    {
        _id: "6",
        country: "France",
        region: "Provence-Alpes-Côte d'Azur",
        town: "Marseille",
        localization: "Marseille, France, Provence-Alpes-Côte d'Azur, Provence-Alpes-Cote d'Azur, Provence Alpes Côte d'Azur, Provence Alpes Cote d'Azur ",
        category: "Hebergements",
        tags: ["Tous", "Romantique"],
        imgUrl: "../../../assets/img/france/marseille/hebergements/hotel_les_mouettes.jpg",
        name: "Hôtel Les mouettes",
        price: 76,
        stars: 4.0,
        description: " Bienvenue aux couples ",
        available: true,
        recorded: false,
        isHebergement: true,
    },
    {
        _id: "7",
        country: "France",
        region: "Provence-Alpes-Côte d'Azur",
        town: "Marseille",
        localization: "Marseille, France, Provence-Alpes-Côte d'Azur, Provence-Alpes-Cote d'Azur, Provence Alpes Côte d'Azur, Provence Alpes Cote d'Azur ",
        category: "Hebergements",
        tags: ["Tous", "Romantique", "Animaux Autorisés"],
        imgUrl: "../../../assets/img/france/marseille/hebergements/hotel_de_la_mer.jpg",
        name: "Hôtel de La mer",
        price: 46,
        stars: 3.0,
        description: " Bienvenue au bord de la mer ",
        available: true,
        recorded: false,
        isHebergement: true,
    },
    {
        _id: "8",
        country: "France",
        region: "Provence-Alpes-Côte d'Azur",
        town: "Marseille",
        localization: "Marseille, France, Provence-Alpes-Côte d'Azur, Provence-Alpes-Cote d'Azur, Provence Alpes Côte d'Azur, Provence Alpes Cote d'Azur ",
        category: "Hebergements",
        tags: ["Tous", "Economique"],
        imgUrl: "../../../assets/img/france/marseille/hebergements/auberge_le_panier.jpg",
        name: "Auberge Le Panier",
        price: 23,
        stars: 4.0,
        description: "Bienvenue à l'auberge",
        available: true,
        recorded: false,
        isHebergement: true,
    },
    {
        _id: "9",
        country: "France",
        region: "Provence-Alpes-Côte d'Azur",
        town: "Marseille",
        localization: "Marseille, France, Provence-Alpes-Côte d'Azur, Provence-Alpes-Cote d'Azur, Provence Alpes Côte d'Azur, Provence Alpes Cote d'Azur ",
        category: "Hebergements",
        tags: ["Tous", "Romantique"],
        imgUrl: "../../../assets/img/france/marseille/hebergements/hotel_chez_amina.jpg",
        name: "Hôtel chez Amina",
        price: 96,
        stars: 5.0,
        description: " Bienvenue chez Amina ",
        available: true,
        recorded: false,
        isHebergement: true,
    },
    {
        _id: "10",
        country: "France",
        region: "Île-de-France",
        town: "Paris",
        localization: "Paris, France, Île-de-France, Ile-de-France, Île de France, Ile de France",
        category: "Activites",
        tags: ["Tous", "Familial"],
        imgUrl: "../../../assets/img/france/marseille/activites/vieux_port.jpg",
        name: "Vieux Port",
        price: 76,
        stars: undefined,
        description: "La fierté",
        recorded: false,
        isActivite: true,
    },
    {
        _id: "11",
        country: "France",
        region: "Provence-Alpes-Côte d'Azur",
        town: "Marseille",
        localization: "Marseille, France, Provence-Alpes-Côte d'Azur, Provence-Alpes-Cote d'Azur, Provence Alpes Côte d'Azur, Provence Alpes Cote d'Azur ",
        category: "Activites",
        tags: ["Tous", "Economique"],
        imgUrl: "../../../assets/img/france/marseille/activites/fort_de_pomegues.jpg",
        name: "Fort de Pomègues",
        price: 23,
        stars: undefined,
        description: "La Fort",
        recorded: false,
        isActivite: true,
    },
    {
        _id: "12",
        country: "France",
        region: "Provence-Alpes-Côte d'Azur",
        town: "Marseille",
        localization: "Marseille, France, Provence-Alpes-Côte d'Azur, Provence-Alpes-Cote d'Azur, Provence Alpes Côte d'Azur, Provence Alpes Cote d'Azur ",
        category: "Activites",
        tags: ["Tous", "Romantique"],
        imgUrl: "../../../assets/img/france/marseille/activites/iles_du_frioul.jpg",
        name: "Îles du Frioul",
        price: 96,
        stars: undefined,
        description: "L'île paradisiaque'",
        recorded: false,
        isActivite: true,
    },
    {
        _id: "13",
        country: "France",
        region: "Provence-Alpes-Côte d'Azur",
        town: "Marseille",
        localization: "Marseille, France, Provence-Alpes-Côte d'Azur, Provence-Alpes-Cote d'Azur, Provence Alpes Côte d'Azur, Provence Alpes Cote d'Azur ",
        category: "Activites",
        tags: ["Tous", "Familial", "Romantique", "Animaux Autorisés"],
        imgUrl: "../../../assets/img/france/marseille/activites/parc_national_des_calanques.jpg",
        name: "Parc National des Calanques",
        price: 71,
        stars: undefined,
        description: "Le parc",
        recorded: false,
        isActivite: true,
    },
    {
        _id: "14",
        country: "France",
        region: "Provence-Alpes-Côte d'Azur",
        town: "Marseille",
        localization: "Marseille, France, Provence-Alpes-Côte d'Azur, Provence-Alpes-Cote d'Azur, Provence Alpes Côte d'Azur, Provence Alpes Cote d'Azur ",
        category: "Activites",
        tags: ["Tous", "Familial", "Romantique"],
        imgUrl: "../../../assets/img/france/marseille/activites/notre_dame_de_la_garde.jpg",
        name: "Notre-Dame-de-la-Garde",
        price: 128,
        stars: undefined,
        description: "La dame",
        recorded: false,
        isActivite: true,
    },
    {
        _id: "15",
        country: "France",
        region: "Provence-Alpes-Côte d'Azur",
        town: "Marseille",
        localization: "Marseille, France, Provence-Alpes-Côte d'Azur, Provence-Alpes-Cote d'Azur, Provence Alpes Côte d'Azur, Provence Alpes Cote d'Azur ",
        category: "Activites",
        tags: ["Tous", "Familial", "Romantique", "Animaux Autorisés"],
        imgUrl: "../../../assets/img/france/marseille/activites/parc_longchamp.jpg",
        name: "Parc Longchamp",
        price: 68,
        stars: undefined,
        description: "Le Parc",
        recorded: false,
        isActivite: true,
    },
];
//# sourceMappingURL=booking.data.js.map